version: "3"

networks:
  proxy-tier:
    external:
       name: caddy-proxy

services:
  #ยง d(data.config.test.healthcheck.docker.services.hostedLogs.name) + ':'
  wise_healthcheck_hosted_logs:
    expose:
      - 80
    networks:
      - proxy-tier
    environment:
      #ยง "VIRTUAL_HOST: \"" + url(data.config.test.healthcheck.hostedLogs.url.staging).hostname + "\""
      VIRTUAL_HOST: "test.dev.wise.jblew.pl"
      VIRTUAL_NETWORK: "caddy-proxy"
      VIRTUAL_PORT: 80
      #ยง "CADDY_TLS: \"" + (url(data.config.test.healthcheck.hostedLogs.url.staging).protocol === "https:" ? "yes" : "no") + "\""
      CADDY_TLS: "yes"
      CADDY_TIMEOUTS: "read 5m, write 2m"
    restart: always


volumes:
  wise.test.logs: #ยง< d(data.config.test.healthcheck.log.dockerVolume) + ':'
    external: true
